version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    formatter: simple
    filename: "${VOLTTRON_HOME}/volttron.log"

loggers:
  volttron.server:
    level: WARNING
    handlers: [file]
    propagate: no
  volttron.client:
    level: WARNING
    handlers: [ file ]
    propagate: no

root:
  level: WARNING
  handlers: [console, file]
