version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: "${VOLTTRON_HOME}/volttron.log"

loggers:
  volttron:
    level: DEBUG
    handlers: [file]
    propagate: no
  
root:
  level: WARNING
  handlers: [console]