name: Test with latest volttron

on:
  schedule:
    - cron: '0 0 * * 0'


defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: AGENT-OR-LIBRARY-NAME

jobs:
  test-with-latest-volttron:
    # call periodic tests only on develop. ideally we want this file to be only in develop so that github doesn't even
    # schedule this job on other branches.
    if: ${{ github.ref == 'refs/heads/develop' }}
    uses: eclipse-volttron/github-tooling/.github/workflows/run-tests.yml@main
