# .github/workflows/sbom-adhoc.yml
# A template demo adhoc action after running sbom check
name: Adhoc SBOM Action

# on:
#   workflow_run:
#     workflows: [Generate SBOM and VDR]  # Note: no quotes, space is fine
#     types:
#       - completed
#     status:
#       - success
#     # branches:   # This needs to be default branch?
#     #   - '**'

on:
  repository_dispatch:
    types: [sbom-generated]

jobs:
  adhoc-sbom:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Collect SBOM Artifact
        run: |
          mkdir -p ./bom_reports 
          # cp -r ${{ github.event.client_payload.bom-reports-path }}/* ./bom_reports/
          cp ${{ github.event.client_payload.bom-json-path }} ./bom_reports/
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
      
      - name: Install Dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Build Wheel
        run: poetry build -vvv 

      - name: Upload SBOM and VDR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bom-artifacts
          path: ./bom_reports/
      
      - name: Upload dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/
