name: update pyproject.toml version

on:
  pull_request:
    branches:
      - develop
    types: [opened]

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '2.0.1'
  
jobs:
  update-version:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
          
    - name: bump pyproject.toml version
      run: |
        current_version=$(poetry version --short)
        echo $current_version
        poetry version prerelease --no-interaction

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: bumped prerelease version
